// <auto-generated />
using System;
using AsOldAsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsOldAsApp.Migrations
{
    [DbContext(typeof(AsOldAsAppContext))]
    partial class AsOldAsAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataModel.Person", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DataModel.WikiEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WikiEvent");
                });

            modelBuilder.Entity("PersonWikiEvent", b =>
                {
                    b.Property<string>("PeopleEntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WikiEventId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PeopleEntityId", "WikiEventId");

                    b.HasIndex("WikiEventId");

                    b.ToTable("PersonWikiEvent");
                });

            modelBuilder.Entity("PersonWikiEvent", b =>
                {
                    b.HasOne("DataModel.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.WikiEvent", null)
                        .WithMany()
                        .HasForeignKey("WikiEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
